# Generated by Django 2.0.2 on 2018-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=60)),
                ('sending_status', models.BooleanField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
