# Generated by Django 2.0.2 on 2018-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180317_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending_info',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
